<?php

/**
 * @file
 * Implements Alipay Direct Payment in Drupal Commerce checkout.
 */

/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_alipay_direct_commerce_payment_method_info() {
  $payment_methods['alipay_direct'] = array(
    'base' => 'commerce_alipay_direct',
    'title' => t('Alipay Direct'),
    'short_title' => t('Alipay'),
    'description' => t('Alipay Direct Payment'),
    'terminal' => FALSE,
    'offsite' => TRUE,
    'offsite_autoredirect' => TRUE,
  );

  return $payment_methods;
}

/**
 * Returns the default settings for the Alipay Direct payment method.
 */
function commerce_alipay_direct_default_settings() {
  return array(
    'partner' => '',
    'md5_key' => '',
    'sign_type' => 'MD5',
    'ipn_logging' => 'notification',
    'show_payment_instructions' => FALSE,
    'fixed_fee' => FALSE,
  );
}

/**
 * Payment method callback: settings form.
 */
function commerce_alipay_direct_settings_form($settings = array()) {
  $settings = $settings + commerce_alipay_direct_default_settings();

  $form['partner'] = array(
    '#type' => 'textfield',
    '#title' => t('Alipay partner ID'),
    '#description' => t('The number beginning with 2088'),
    '#default_value' => $settings['partner'],
    '#required' => TRUE,
  );
  // Currently only MD5 sign type is supported
  $form['sign_type'] = array(
    '#type' => 'radios',
    '#title' => t('Sign type'),
    '#options' => array(
      'MD5' => 'MD5',
    ),
    '#description' => t('Currently only MD5 sign type is supported.'),
    '#default_value' => $settings['sign_type'],
    '#required' => TRUE,
  );
  $form['md5_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Key'),
    '#description' => t('Verification key for MD5 sign'),
    '#default_value' => $settings['md5_key'],
    '#required' => TRUE,
  );
  $form['ipn_logging'] = array(
    '#type' => 'radios',
    '#title' => t('IPN logging'),
    '#options' => array(
      'notification' => t('Log notifications during IPN validation and processing.'),
      'full_ipn' => t('Log notifications with the full IPN during validation and processing (used for debugging).'),
    ),
    '#default_value' => $settings['ipn_logging'],
  );
  $form['show_payment_instructions'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show a message on the checkout form when Alipay Direct is selected telling the customer to "Continue with checkout to complete payment via Alipay."'),
    '#default_value' => $settings['show_payment_instructions'],
  );
  $form['fixed_fee'] = array(
    '#type' => 'checkbox',
    '#title' => t('Set total fee to 0.01 CNY.'),
    '#description' => t('<strong class="warning">Warning:</strong> This option is only for development purpose, and should <b>never</b> be enabled on a production site.'),
    '#default_value' => $settings['fixed_fee'],
  );

  return $form;
}

/**
 * Payment method callback: submit form, adds a message to the submission form if enabled in
 * the payment method settings.
 */
function commerce_alipay_direct_submit_form($payment_method, $pane_values, $checkout_pane, $order) {
  $form = array();

  if (!empty($payment_method['settings']['show_payment_instructions'])) {
    $form['alipay_direct_information'] = array(
      '#markup' => '<span class="commerce-alipay-direct-info">' . t('(Continue with checkout to complete payment via Alipay.)') . '</span>',
    );
  }

  return $form;
}

/**
 * Payment method callback: submit form validation.
 */
function commerce_alipay_direct_submit_form_validate($payment_method, $pane_form, $pane_values, $order, $form_parents = array()) {
  // Return an error if the enabling action's settings haven't been configured.
  if (empty($payment_method['settings']['partner'])) {
    drupal_set_message(t('Alipay Direct is not configured for use. No Alipay partner has been specified.'), 'error');
    return FALSE;
  }
}

/**
 * Payment method callback: redirect form, a wrapper around the module's general
 * use function for building a Direct form.
 *
 * @see commerce_payment_redirect_pane_checkout_form() for cancel_return and return
 */
function commerce_alipay_direct_redirect_form($form, &$form_state, $order, $payment_method) {
  $settings = array(
    // Return to the previous page when payment is canceled, currently not used for Alipay.
    'cancel_return' => url('checkout/' . $order->order_id . '/payment/back/' . $order->data['payment_redirect_key'], array('absolute' => TRUE)),

    // Returns to the redirect page for processing successful payments.
    'return' => url('checkout/' . $order->order_id . '/payment/return/' . $order->data['payment_redirect_key'], array('absolute' => TRUE)),

    // Specify the current payment method instance ID in the notify_url
    'payment_method' => $payment_method['instance_id'],
  );

  return commerce_alipay_direct_order_form($form, $form_state, $order, $payment_method['settings'] + $settings);
}

/**
 * Payment method callback: redirect form return validation.
 *
 * This callback will be ignored as commerce_marketplace_payment_redirect_pane_checkout_form() won't be called
 * when customer redirected from Alipay due to <b>Sync Notification</b> expressed by <code>return_url</code>,
 * if the given order had already successfully processed by Alipay asynchronous IPN,
 * the order will be in pending state, and had no access to the checkout page.
 *
 * @see commerce_checkout_router();
 * @see commerce_marketplace_checkout_router();
 * @see commerce_checkout_page_access()
 * @see commerce_payment_redirect_pane_checkout_form()
 * @see commerce_marketplace_payment_redirect_pane_checkout_form()
 */
function commerce_alipay_direct_redirect_form_validate($order, $payment_method) {
  watchdog('commerce_alipay_direct', 'order id' . $order->order_id, array(), WATCHDOG_NOTICE);

  if (!empty($payment_method['settings']['ipn_logging']) && $payment_method['settings']['ipn_logging'] == 'full_ipn') {
    watchdog('commerce_alipay_direct', 'Customer returned from Alipay with the following GET data:!ipn_data', array('!ipn_data' => '<pre>' . check_plain(print_r($_GET, TRUE)) . '</pre>'), WATCHDOG_NOTICE);
  }

  $ipn = $_GET;
  // Remove 'q' parameter (e.g., $_GET['q']=checkout/28/payment/return/hzufsIv1NnT_v_-xyDuku2s0bR5_F3VyI7JQzU6-Zi8)
  // added in by Drupal.
  unset($ipn['q']);

  // Exit now if the $ipn was empty.
  if (empty($ipn)) {
    watchdog('commerce_alipay_direct', 'IPN URL accessed with no GET data submitted.', array(), WATCHDOG_WARNING);
    return FALSE;
  }

  if ($ipn['is_success'] != 'T') {
    watchdog('commerce_alipay_direct', 'The call to Alipay gateway is failed.', array(), WATCHDOG_NOTICE);
    return FALSE;
  }

  // Attempt to verify IPN.
  if (commerce_alipay_verify_ipn($ipn, $payment_method['settings']) === FALSE) {
    watchdog('commerce_alipay_direct', 'Invalid IPN received and ignored.', array(), WATCHDOG_ALERT);
    return FALSE;
  }

  // This may be an unnecessary step, but if for some reason the user does end
  // up returning at the success URL with a Failed payment, go back.
  if (!empty($_GET['trade_status']) && !in_array($_GET['trade_status'], array('TRADE_FINISHED', 'TRADE_SUCCESS'))) {
    return FALSE;
  }
}

/**
 * Payment method callback: validate an IPN based on out_trade_no, seller_id,
 * total_fee, and other parameters as possible.
 */
function commerce_alipay_direct_alipay_ipn_validate($order, $payment_method, $ipn) {
  if ($ipn['seller_id'] != $payment_method['settings']['partner']) {
    commerce_payment_redirect_pane_previous_page($order);
    watchdog('commerce_alipay_direct', 'IPN rejected: invalid seller id specified (@seller_id); must match the partner seller id on the Alipay account.', array('@seller_id' => $ipn['seller_id']), WATCHDOG_NOTICE);
    return FALSE;
  }

  // Validate total_fee.
  // This may be an unnecessary step, but if merchant security keys leaked,
  // this validation could prevent attacker from completing an order with pretty
  // low price like 0.01.
  if (!$payment_method['settings']['fixed_fee']) {
    // Process given total amount.
    $total_amount = commerce_currency_decimal_to_amount($ipn['total_fee'], ALIPAY_CURRENCY);
    // Process original total amount.
    $original_total_amount = entity_metadata_wrapper('commerce_order', $order)->commerce_order_total->amount->value();

    if ($total_amount != $original_total_amount) {
      commerce_payment_redirect_pane_previous_page($order);
      $params = array( '@total_fee' => $ipn['total_fee'], '@total_amount' => $total_amount, '@amount' => $original_total_amount);
      watchdog('commerce_alipay_direct', 'IPN rejected: invalid total fee specified (@total_fee -> @total_amount); must match the order total @amount.', $params, WATCHDOG_NOTICE);
      return FALSE;
    }
  }

  // Prepare the IPN data for inclusion in the watchdog message if enabled.
  $ipn_data = '';

  if (!empty($payment_method['settings']['ipn_logging']) && $payment_method['settings']['ipn_logging'] == 'full_ipn') {
    $ipn_data = '<pre>' . check_plain(print_r($ipn, TRUE)) . '</pre>';
  }

  // Log a message.
  watchdog('commerce_alipay_direct', 'IPN validated for Order @order_number with Trade @trade_no.!ipn_data', array('@order_number' => $order->order_number, '@trade_no' => $ipn['trade_no'], '!ipn_data' => $ipn_data), WATCHDOG_NOTICE);
}

/** Builds a Direct Payment form from an order object.
 *
 * @param $order
 *   The fully loaded order being paid for.
 *
 * @return
 *   A readable form array.
 */
function commerce_alipay_direct_order_form($form, &$form_state, $order, $settings) {
  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);

  $amount = $order_wrapper->commerce_order_total->amount->value();
  $data = array(
    'service' => ALIPAY_SERVICE_DIRECT,
    'partner' => $settings['partner'],
    'seller_id' => $settings['partner'],
    'payment_type' => '1',
    'notify_url' => commerce_alipay_ipn_url($settings['payment_method']),
    'return_url' => $settings['return'],
    'out_trade_no' => commerce_alipay_out_trade_number($order),
    'total_fee' => commerce_alipay_amount_to_decimal($amount, ALIPAY_CURRENCY),
    'subject' => 'donation subject#', // TODO: subject
    'body' => 'donation body@', // TODO: body
    'show_url' => 'http://localhost/product/10001', // TODO: show url
    '_input_charset' => ALIPAY_CHARSET,
    'it_b_pay' => '15m', // TODO: timeout for stock
  );

  drupal_alter('commerce_alipay_direct_order_form_data', $data, $order);

  // In debug mode.
  if ($settings['fixed_fee']) {
    $data['total_fee'] = 0.01;
  }

  // Sign request data.
  $signed_data = commerce_alipay_sign($data, $settings);

  $form['#action'] = ALIPAY_SERVER;
  $form['#method'] = 'post';

  foreach ($signed_data as $name => $value) {
    $form[$name] = array('#type' => 'hidden', '#value' => $value);
  }

  $form['submit'] = array(
    '#type' => 'button',
    '#value' => t('Proceed to Alipay'),
  );

  return $form;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function commerce_alipay_direct_form_commerce_checkout_form_payment_alter(&$form, &$form_state) {
  // If this payment form is for Alipay
  if (strpos($form['#action'], ALIPAY_SERVER) === 0) {
    // Remove name attribute from the submit button for Alipay,
    // see _form_builder_handle_input_element() and form_builder() in form.inc.
    $form['submit']['#input'] = FALSE;
    unset($form['submit']['#name']);

    // Hide form elements for Alipay
    $form['form_build_id']['#access'] = FALSE;
    $form['form_token']['#access'] = FALSE;
    $form['form_id']['#access'] = FALSE;
  }
}
